[

    {
        type: "COMIC",
        name: "Sherlock Frankenstein and the Legion of Evil",
        description: "Lucy Weber, daughter of the Black Hammer, grew up to become an investigative reporter for the Global Planet. Now she's on the hunt for the true story about what happened to Spiral City's superheroes after they defeated Anti-God and saved the world. All answers seem to lie with the dangerous super villain tenants of Spiral City's infamous asylum. As she gets closer to the truth she uncovers the dark origin stories of some of her father's greatest foes, and learns how they tie into the puzzle of what happened to Spiral City's greatest hero.",
        imagePath: "data/images/comic-Sherlock-Frankenstein.jpg",
        price: 5.99,
        year: 2017,
    },
    {
        type: "COMIC",
        name: "Tom Clancy's The Division - Extremis Malis",
        description: "Months after a bioweapon attack devastated New York City, the Division agents are the last hope of a United States struggling to hold itself together. During a mission gone horribly wrong, Division Agent Caleb Dunne's partner is gruesomely killed and Dunne vows to track down the mysterious woman responsible. As he gathers clues to her whereabouts, he uncovers a grave threat to a nation already on the brink of total collapse.",
        imagePath: "data/images/comic-The-Division.jpg",
        price: 3.99,
        year: 2019,
    },
    {
        type: "POSTER",
        name: "Dulce de Maracuyá 1",
        description: "They say that 'we are all artists when we have a broken heart'.This is a small tribute to love. That love that squeezes our soul and leaves us breathless. That love from which we cannot escape because in reality ... we do not want to escape.It acts like the waves of the sea, seemingly gentle while we rely on its paradisiacal beaches, but suddenly end up dragging us to its most inhospitable depths.The love that consumes us and that enlivens us, that stabs us and caresses us, that cracks us and also heals us.",
        imagePath: "data/images/Post-Maracuya-1.jpg",
        price: 16.99,
        year: 2018,
    },
    {
        type: "POSTER",
        name: "Dulce de Maracuyá 2",
        description: "They say that 'we are all artists when we have a broken heart'.This is a small tribute to love. That love that squeezes our soul and leaves us breathless. That love from which we cannot escape because in reality ... we do not want to escape.It acts like the waves of the sea, seemingly gentle while we rely on its paradisiacal beaches, but suddenly end up dragging us to its most inhospitable depths.The love that consumes us and that enlivens us, that stabs us and caresses us, that cracks us and also heals us.",
        imagePath: "data/images/Post-Maracuya-2.jpg",
        price: 16.99,
        year: 2018,
    },
    {
        type: "POSTER",
        name: "Dulce de Maracuyá 3",
        description: "They say that 'we are all artists when we have a broken heart'.This is a small tribute to love. That love that squeezes our soul and leaves us breathless. That love from which we cannot escape because in reality ... we do not want to escape.It acts like the waves of the sea, seemingly gentle while we rely on its paradisiacal beaches, but suddenly end up dragging us to its most inhospitable depths.The love that consumes us and that enlivens us, that stabs us and caresses us, that cracks us and also heals us.",
        imagePath: "data/images/Post-Maracuya-3.jpg",
        price: 16.99,
        year: 2018,
    },
    {
        type: "STICKER",
        name: "Some Fox",
        description: "Just be you. Don't be afraid",
        imagePath: "data/images/St-fox.jpg",
        price: 2.40,
        year: 2018,
    },
    {
        type: "STICKER",
        name: "Some Frog",
        description: "Just be you. Don't be afraid",
        imagePath: "data/images/St-frog.jpg",
        price: 3.20,
        year: 2018,
    },
    {
        type: "STICKER",
        name: "Some Hamster",
        description: "Just be you. Don't be afraid",
        imagePath: "data/images/St-hamster.jpg",
        price: 2.40,
        year: 2018,
    },
    {
        type: "STICKER",
        name: "Some Pig",
        description: "Just be you. Don't be afraid",
        imagePath: "data/images/St-pig.jpg",
        price: 2.40,
        year: 2018,
    },
    {
        type: "STICKER",
        name: "Some Rat",
        description: "Just be you. Don't be afraid",
        imagePath: "data/images/St-rat.jpg",
        price: 1.20,
        year: 2018,
    },
    {
        type: "STICKER",
        name: "Some Snake",
        description: "Just be you. Don't be afraid",
        imagePath: "data/images/St-snake.jpg",
        price: 3.40,
        year: 2018,
    },
    {
        type: "STICKER",
        name: "Some Tiger",
        description: "Just be you. Don't be afraid",
        imagePath: "data/images/St-tiger.jpg",
        price: 2.25,
        year: 2018,
    },
    {
        type: "STICKER",
        name: "Some Tortoise",
        description: "Just be you. Don't be afraid",
        imagePath: "data/images/St-Tortuga.jpg",
        price: 3.60,
        year: 2018,
    }
]