module.exports = [

{
    type: "COMIC",
    name: "ANTHEM - A New Verse",
    description: "The Anthem comic series follows a boy named Kismet who is rescued from an ambush by Yarrow—one of the javelin pilots known as Freelancers. Now an orphan, Kismet and his adoptive sister Jani must build a better future for themselves, and humanity, in a world filled with danger.",
    imagePath: "data/images/comic-Anthem.jpg",
    price: 5.25,
    year: 2019,
},
{
    type: "COMIC",
    name: "B.P.R.D - The Devil You Know",
    description: "The Devil You Know is the final cycle of the ongoing B.P.R.D. stories, continuing on from where the Hell on Earth cycle left off. This story cycle is co-written by Scott Allie, following the departure of John Arcudi. The title was formally announced on February 24, 2017, in a teaser image from Multiversity Comics.",
    imagePath: "data/images/comic-BPRD-The-Devil-You-Know.jpg",
    price: 3.99,
    year: 2017,
},
{
    type: "COMIC",
    name: "Calamity Kate",
    description: "Kate Strand reboots her destructive life and moves to LA to be the superhero she always wanted to be--Calamity Kate: gun-toting monster killer. With her latest career change, she faces new challenges, relationships, and competition; desperate to show she's worth a damn in a world overrun by zombies, vampires, demons, goblins, and the ultimate monster bounty: the Seven Fabled Beasts of Yore.",
    imagePath: "data/images/comic-Clamity-Kate.jpg",
    price: 3.99,
    year: 2019,
},
{
    type: "COMIC",
    name: "Sherlock Frankenstein and the Legion of Evil",
    description: "Lucy Weber, daughter of the Black Hammer, grew up to become an investigative reporter for the Global Planet. Now she's on the hunt for the true story about what happened to Spiral City's superheroes after they defeated Anti-God and saved the world. All answers seem to lie with the dangerous super villain tenants of Spiral City's infamous asylum. As she gets closer to the truth she uncovers the dark origin stories of some of her father's greatest foes, and learns how they tie into the puzzle of what happened to Spiral City's greatest hero.",
    imagePath: "data/images/comic-Sherlock-Frankenstein.jpg",
    price: 5.99,
    year: 2017,
},
{
    type: "COMIC",
    name: "Tom Clancy's The Division - Extremis Malis",
    description: "Months after a bioweapon attack devastated New York City, the Division agents are the last hope of a United States struggling to hold itself together. During a mission gone horribly wrong, Division Agent Caleb Dunne's partner is gruesomely killed and Dunne vows to track down the mysterious woman responsible. As he gathers clues to her whereabouts, he uncovers a grave threat to a nation already on the brink of total collapse.",
    imagePath: "data/images/comic-The-Division.jpg",
    price: 3.99,
    year: 2019,
},
{
    type: "POSTER",
    name: "Defenders of the territory against extractivism and territorial control",
    description: "From the imposition of development models that ignore other ways of living in the world, energy mining extractivist projects come to be imposed on the communities and towns that inhabit these territories. We want to highlight the work of women who, from their community work, contribute to the defense of the territory and the organization of their communities. And that as a para-state response they must also resist illegal armed groups that impose territorial control generally in favor of energy mining development projects.",
    imagePath: "data/images/Post-Guerra-Extract.jpg",
    price: 12.25,
    year: 2019,
},
{
    type: "POSTER",
    name: "Memory of murdered social fighters",
    description: "We want to make an exercise in memory of all the women who's lives have been taken because of their work and fight in defense of their towns and territories. Unfortunately in Colombia, Latin America and other latitudes of the world there are innumerable voices of women who have been silenced, in their struggle to live with dignity. That's why we make a call to exalt their courage, their stories and actions, which in one way or another changed the history of the community that they habited and inhabited them.",
    imagePath: "data/images/Post-Guerra-Lideres.jpg",
    price: 12.25,
    year: 2019,
},
{
    type: "POSTER",
    name: "Solidarity and Migrations",
    description: "In this political moment, we also want to represent the organizational and solidarity initiatives that arise in different parts of the world from the arrival or passage of migrants, from other contexts, who have been forced to leave their territories of origin because of social and economic conflicts that result from imperialist policies and their monopolistic and exclusive economic model.",
    imagePath: "data/images/Post-Guerra-Migraciones.jpg",
    price: 12.25,
    year: 2019,
},
{
    type: "POSTER",
    name: "Dulce de Maracuyá 1",
    description: "They say that 'we are all artists when we have a broken heart'.This is a small tribute to love. That love that squeezes our soul and leaves us breathless. That love from which we cannot escape because in reality ... we do not want to escape.It acts like the waves of the sea, seemingly gentle while we rely on its paradisiacal beaches, but suddenly end up dragging us to its most inhospitable depths.The love that consumes us and that enlivens us, that stabs us and caresses us, that cracks us and also heals us.",
    imagePath: "data/images/Post-Maracuya-1.jpg",
    price: 16.99,
    year: 2018,
},
{
    type: "POSTER",
    name: "Dulce de Maracuyá 2",
    description: "They say that 'we are all artists when we have a broken heart'.This is a small tribute to love. That love that squeezes our soul and leaves us breathless. That love from which we cannot escape because in reality ... we do not want to escape.It acts like the waves of the sea, seemingly gentle while we rely on its paradisiacal beaches, but suddenly end up dragging us to its most inhospitable depths.The love that consumes us and that enlivens us, that stabs us and caresses us, that cracks us and also heals us.",
    imagePath: "data/images/Post-Maracuya-2.jpg",
    price: 16.99,
    year: 2018,
},
{
    type: "POSTER",
    name: "Dulce de Maracuyá 3",
    description: "They say that 'we are all artists when we have a broken heart'.This is a small tribute to love. That love that squeezes our soul and leaves us breathless. That love from which we cannot escape because in reality ... we do not want to escape.It acts like the waves of the sea, seemingly gentle while we rely on its paradisiacal beaches, but suddenly end up dragging us to its most inhospitable depths.The love that consumes us and that enlivens us, that stabs us and caresses us, that cracks us and also heals us.",
    imagePath: "data/images/Post-Maracuya-3.jpg",
    price: 16.99,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Dog",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-dog.jpg",
    price: 2.40,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Fish",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-fish.jpg",
    price: 2.40,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Seal",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-foca.jpg",
    price: 3.40,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Fox",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-fox.jpg",
    price: 2.40,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Frog",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-frog.jpg",
    price: 3.20,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Hamster",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-hamster.jpg",
    price: 2.40,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Pig",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-pig.jpg",
    price: 2.40,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Rat",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-rat.jpg",
    price: 1.20,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Snake",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-snake.jpg",
    price: 3.40,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Tiger",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-tiger.jpg",
    price: 2.25,
    year: 2018,
},
{
    type: "STICKER",
    name: "Some Tortoise",
    description: "Just be you. Don't be afraid",
    imagePath: "data/images/St-Tortuga.jpg",
    price: 3.60,
    year: 2018,
}
]